config:
  locations:
    spawn: 'world,0,0,0,0,0'
    npcs:
      factions:
        location: 'world,0,0,0,0,0'
        skin: dfc994fc-89f9-45a6-8886-af756ff7c7af
      duels:
        location: 'world,0,0,0,0,0'
        skin: dfc994fc-89f9-45a6-8886-af756ff7c7af
      pvp:
        location: 'world,0,0,0,0,0'
        skin: dfc994fc-89f9-45a6-8886-af756ff7c7af